### ISSUE TITLE
Snakemake fails to generate HTML report

### ISSUE THREAD

**Issue by icaromsc** [icaromsc/WGCA#1]
I got the following error when i tried to run  

`snakemake -n --report myresults.html`

```
Traceback (most recent call last):
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/snakemake/report/__init__.py", line 224, in code
    lexer = get_lexer_by_name(language)
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/pygments/lexers/__init__.py", line 107, in get_lexer_by_name
    raise ClassNotFound('no lexer for alias %r found' % _alias)
pygments.util.ClassNotFound: no lexer for alias None found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/snakemake/__init__.py", line 547, in snakemake
    export_cwl=export_cwl)
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/snakemake/workflow.py", line 514, in execute
    auto_report(dag, report)
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/snakemake/report/__init__.py", line 577, in auto_report
    pygments_css=HtmlFormatter(style="trac").get_style_defs('.source')))
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/snakemake/report/report.html", line 474, in top-level template code
    {{ rule.code()|safe }}
  File "/home/icaro/miniconda3/envs/jamira_up/lib/python3.6/site-packages/snakemake/report/__init__.py", line 226, in code
    except pygments.utils.ClassNotFound:
NameError: name 'pygments' is not defined
```

**Comment by icaromsc** [comment]
Os autores da ferramenta SnakeMake comentaram que esse é um bug referente a versão 5.26.1 e que será resolvido no próximo release da ferramenta
https://github.com/snakemake/snakemake/issues/682

**Comment by icaromsc** [comment]
Resolvido após atualização para SnakeMake 6.0.5
